apiVersion: v1
kind: Service
metadata:
  name: rails-k8s-basic-example-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: rails-k8s-basic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
